# This is a basic workflow to help you get started with Actions

name: BobTest

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  thing: 
    runs-on: ubuntu-latest
    steps: 
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "Hi!"
